version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      timezone: Asia/Jakarta
    groups:
      artifacts:
        patterns: [actions/*-artifact, actions/deploy-pages]
      dockers:
        patterns: [docker/*]
      utilities:
        patterns: [actions/checkout, actions/github-script, actions/attest-*]
