name: Release

on:
  workflow_call:
    inputs:
      branch:
        description: 'Branch target'
        default: main
        type: string
      composer-cache-dir:
        required: true
        type: string
      composer-cache-key:
        default: php-${{ inputs.php-version }}
        type: string
      needs-bun:
        default: false
        type: boolean
      needs-npm:
        default: false
        type: boolean
      needs-pnpm:
        default: false
        type: boolean
      node-pm-name:
        required: true
        type: string
      node-pm-version:
        required: true
        type: string
      php-version:
        default: '8.2'
        type: string
      sentry-project:
        required: false
        type: string
      target-env:
        description: 'Build target'
        default: testing
        type: string
      target-url:
        description: 'URL target'
        default: http://localhost:8000
        type: string
    outputs:
      app-key:
        value: ${{ jobs.build.outputs.app-key }}
      target-env:
        value: ${{ jobs.build.outputs.target-env }}
      target-url:
        value: ${{ jobs.build.outputs.target-url }}
    secrets:
      ACCESS_TOKEN:
        required: false
      SENTRY_AUTH_TOKEN:
        required: false
      SENTRY_DSN:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build for `${{ inputs.target-env }}`
    outputs:
      app-key: ${{ steps.app.outputs.generated-key }}
      target-env: ${{ inputs.target-env }}
      target-url: ${{ inputs.target-url }}

    env:
      APP_ENV: ${{ inputs.target-env }}
      APP_URL: ${{ inputs.target-url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Setup bun
        if: ${{ inputs.needs-bun }}
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ inputs.node-pm-version }}

      - name: Setup node.js
        if: ${{ inputs.needs-npm }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ inputs.node-pm-version }}

      - name: Setup pnpm
        if: ${{ inputs.needs-pnpm }}
        uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2.1.0
        with:
          cache: true
          runtime: 'node@24'
          version: ${{ inputs.node-pm-version }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          php-version: ${{ inputs.php-version }}

      - name: Prepare Composer Cache
        uses: actions/cache@v6
        with:
          path: ${{ inputs.composer-cache-dir }}
          key: ${{ inputs.composer-cache-key }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ inputs.composer-cache-key }}-composer-

      - name: Install dependencies
        id: app
        run: |
          ${{ inputs.node-pm-name }} ci
          [[ -f .github/.env.example ]] && cp .github/.env.example .env
          composer update --prefer-dist --no-scripts --no-interaction --no-progress --ansi
          echo "generated-key=$(php artisan key:generate --show)" >> $GITHUB_OUTPUT
          touch database/database.sqlite

      - name: Dump Autoload
        env:
          APP_KEY: ${{ steps.app.outputs.generated-key }}
        run: |
          composer dump-autoload

      - name: Deploy Info
        if: ${{ env.APP_ENV != 'testing' && env.APP_URL != 'http://localhost:8000' }}
        env:
          BRANCH: ${{ inputs.branch }}
        run: |
          composer dep deploy:info env=$APP_ENV -- --branch $BRANCH

      - name: Build frontend
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_ORG: ${{ github.repository_owner }}
          SENTRY_PROJECT: ${{ inputs.sentry-project }}
        run: |
          ${{ inputs.node-pm-name }} run build --mode ${{ env.APP_ENV }}

      - name: Store assets
        uses: actions/upload-artifact@v7
        with:
          name: build-${{ env.APP_ENV }}
          path: |
            public/build
            public/vendor
