name: Prepare

on:
  workflow_call:
    inputs:
      base-branch:
        required: false
        type: string
        default: ${{ github.event.repository.default_branch || 'main' }}
      php-version:
        required: false
        type: string
        default: ${{ vars.PHP_VERSION || '8.1' }}
      node-version:
        required: false
        type: string
        default: ${{ vars.NODE_VERSION || 'lts/*' }}
      pnpm-version:
        required: false
        type: string
        default: ${{ vars.PNPM_VERSION || '10.12.4' }}
      bun-version:
        required: false
        type: string
        default: ${{ vars.BUN_VERSION || '1.3.10' }}
      target-env:
        required: false
        type: string
    outputs:
      # Project
      project-repo-name:
        value: ${{ jobs.environments.outputs.project-repo-name }}
        description: The lower-case name of the project repository.
      project-branch-name:
        value: ${{ jobs.environments.outputs.project-branch-name }}
        description: The name of the project branch.
      project-version:
        value: ${{ jobs.environments.outputs.project-version }}
        description: The version of the project.
      # PHP Project
      needs-php:
        value: ${{ jobs.environments.outputs.needs-php }}
        description: Whether the project needs PHP.
      needs-composer:
        value: ${{ jobs.environments.outputs.needs-composer }}
        description: Whether the project needs Composer.
      needs-wpcli:
        value: ${{ jobs.environments.outputs.needs-wpcli }}
        description: Whether the project needs WP-CLI.
      is-laravel:
        value: ${{ jobs.environments.outputs.is-laravel }}
        description: Whether the project is a Laravel project.
      composer-cache-dir:
        value: ${{ jobs.environments.outputs.composer-cache-dir }}
        description: The cache directory for Composer.
      wpcli-cache-dir:
        value: ${{ jobs.environments.outputs.wpcli-cache-dir }}
        description: The cache directory for WP-CLI.
      # Node Project
      needs-node:
        value: ${{ jobs.environments.outputs.needs-node }}
      needs-pnpm:
        value: ${{ jobs.environments.outputs.needs-pnpm }}
        description: Whether the project needs pnpm.
      needs-bun:
        value: ${{ jobs.environments.outputs.needs-bun }}
        description: Whether the project needs Bun.
      node-pm-name:
        value: ${{ jobs.environments.outputs.node-pm-name }}
        description: "The name of the Node.js package manager: npm, pnpm & bun."
      node-pm-version:
        value: ${{ jobs.environments.outputs.node-pm-version }}
        description: The version of the Node.js package manager.
      # Test Reports
      has-codecov:
        value: ${{ jobs.environments.outputs.has-codecov }}
        description: Whether the project has Codecov.
      has-coveralls:
        value: ${{ jobs.environments.outputs.has-coveralls }}
        description: Whether the project has Coveralls.
      should-reports:
        value: ${{ jobs.environments.outputs.should-reports }}
        description: Whether test coverage reports should be generated.
      # Workflow
      has-previous:
        value: ${{ jobs.environments.outputs.has-previous }}
        description: Whether the workflow has a previous runs.
      previous-run:
        value: ${{ jobs.environments.outputs.previous-run }}
        description: "The previous workflow run object: { sha, message, artifacts: {id, name}[] }."
      # Code base
      changed-files:
        value: ${{ jobs.environments.outputs.changed-files }}
        description: List of changed files.
      should-build:
        value: ${{ jobs.environments.outputs.should-build }}
        description: Whether should run the build.
      should-deploy:
        value: ${{ jobs.environments.outputs.should-deploy }}
        description: Whether should run the deployment.
      should-tests:
        value: ${{ jobs.environments.outputs.should-tests }}
        description: Whether should run the tests.
    secrets:
      CODECOV_TOKEN:
        required: false
      COVERALLS_REPO_TOKEN:
        required: false

jobs:
  labels:
    name: Labels
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Check configs
        id: check
        run: |
          if [ -f ".github/labeler.yml" ] || [ -f ".github/labeler.yaml" ]; then
            echo "should-label=1" >> $GITHUB_OUTPUT
          fi

      - name: Labeler
        if: steps.check.outputs.should-label == '1'
        uses: actions/labeler@v6
        with:
          dot: true

  environments:
    name: Environments
    runs-on: ubuntu-latest
    outputs:
      # Project
      project-repo-name: ${{ steps.project.outputs.repo-name }}
      project-branch-name: ${{ steps.project.outputs.branch-name }}
      project-version: ${{ steps.project.outputs.version }}
      pr-number: ${{ steps.project.outputs.pr-number }}
      # PHP Project
      needs-php: ${{ steps.php.outputs.needs-php || '0' }}
      needs-composer: ${{ steps.php.outputs.needs-composer || '0' }}
      needs-wpcli: ${{ steps.php.outputs.needs-wpcli || '0' }}
      is-laravel: ${{ steps.php.outputs.is-laravel || '0' }}
      composer-cache-dir: ${{ steps.cache-dirs.outputs.composer-dir }}
      wpcli-cache-dir: ${{ steps.cache-dirs.outputs.wpcli-dir }}
      # Node Project
      node-pm-name: ${{ steps.node.outputs.pm-name }}
      node-pm-version: ${{ steps.node.outputs.pm-version }}
      needs-node: ${{ steps.node.outputs.needs-node || '0' }}
      needs-pnpm: ${{ steps.node.outputs.needs-pnpm || '0' }}
      needs-bun: ${{ steps.node.outputs.needs-bun || '0' }}
      # Test Reports
      has-codecov: ${{ steps.reports.outputs.has-codecov || '0' }}
      has-coveralls: ${{ steps.reports.outputs.has-coveralls || '0' }}
      should-reports: ${{ steps.reports.outputs.should-reports || '0' }}
      # Workflow
      has-previous: ${{ steps.previous-run.outputs.available || '0' }}
      previous-run: ${{ steps.previous-run.outputs.result }}
      # Code base
      has-changes: ${{ steps.changed-files.outputs.available || '0' }}
      changed-files: ${{ steps.changed-files.outputs.result }}
      should-build: ${{ steps.changed-files.outputs.should-build || '0' }}
      should-deploy: ${{ steps.changed-files.outputs.should-deploy || '0' }}
      should-tests: ${{ steps.changed-files.outputs.should-tests || '0' }}

    steps:
      - name: Checkout head repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          # persist-credentials: false

      - name: Checkout actions repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          repository: projek-xyz/actions
          ref: prepare/buildable-testable-deployable
          # persist-credentials: false
          path: .github/xyz-actions
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            .github/scripts/changed-files.js
            .github/scripts/previous-run.js

      - name: PHP Requirements
        id: php
        run: |
          # Whether it's requires PHP runtime
          NEEDS_COMPOSER=$(test -f ./composer.json && echo 1 || echo 0)
          NEEDS_WPCLI=$(test -f ./wp-cli.yml && echo 1 || echo 0)
          PHP_TOOLS=

          # Whether the repository has composer.json
          echo "needs-composer=$(test -f ./composer.json && echo 1 || echo 0)" >> $GITHUB_OUTPUT

          # Whether the repository has wp-cli.yml
          echo "needs-wpcli=${NEEDS_WPCLI}" >> $GITHUB_OUTPUT

          # Whether the repository is a laravel project
          echo "is-laravel=$(test -x ./artisan && echo 1 || echo 0)" >> $GITHUB_OUTPUT

          if [[ $NEEDS_COMPOSER -eq 1 ]]; then PHP_TOOLS="${PHP_TOOLS:+$PHP_TOOLS,}composer"; fi
          if [[ $NEEDS_WPCLI -eq 1 ]]; then PHP_TOOLS="${PHP_TOOLS:+$PHP_TOOLS,}wp-cli"; fi

          echo "needs-php=$([ -n "$PHP_TOOLS" ] && echo 1 || echo 0)" >> $GITHUB_OUTPUT
          echo "php-tools=${PHP_TOOLS}" >> $GITHUB_OUTPUT

      - name: Node Requirements
        id: node
        run: |
          # Whether it's requires Node runtime'
          PM_NAME=
          PM_VERSION=

          # Whether the repository has package.json
          NEEDS_NODE=$(test -f ./package.json && echo 1 || echo 0)

          # Whether the repository require a pnpm
          NEEDS_PNPM=$(test -f ./pnpm-lock.yaml && echo 1 || echo 0)

          # Whether the repository require a bun
          NEEDS_BUN=$(test -f ./bun.lock && echo 1 || echo 0)

          if [[ $NEEDS_NODE -eq 1 ]]; then PM_NAME=npm; fi
          if [[ $NEEDS_PNPM -eq 1 ]]; then PM_NAME=pnpm; fi
          if [[ $NEEDS_BUN -eq 1 ]]; then PM_NAME=bun; fi

          if [[ $NEEDS_NODE -eq 1 ]]; then
            pkg_namager=$(jq -r '.packageManager // ""' package.json)

            if [[ -n $pkg_namager ]]; then
              arr=(${pkg_namager//@/ })

              PM_NAME=${arr[0]}
              PM_VERSION=${arr[1]}
            fi
          fi

          echo "needs-node=$NEEDS_NODE" >> $GITHUB_OUTPUT
          echo "needs-pnpm=$NEEDS_PNPM" >> $GITHUB_OUTPUT
          echo "needs-bun=$NEEDS_BUN" >> $GITHUB_OUTPUT
          echo "pm-name=$PM_NAME" >> $GITHUB_OUTPUT
          echo "pm-version=$PM_VERSION" >> $GITHUB_OUTPUT

      - name: Project
        id: project
        env:
          HAS_NODE: ${{ steps.node.outputs.needs-node }}
          BASE_BRANCH: ${{ inputs.base-branch }}
        run: |
          # Extract repository name and convert to lowercase
          REPO_NAME=$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')

          # Extract repository branch name
          BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF_NAME}}

          # Extract branch slug
          BRANCH_SLUG=$(echo $BRANCH_NAME | sed 's#/#_#g; s#\[##g; s#\]##g')
          BRANCH_SLUG=${BRANCH_SLUG:0:20}.${GITHUB_SHA:0:8}

          PR_NUMBER=$([[ $BRANCH_NAME =~ "/merge" ]] && echo "${BRANCH_NAME//\/merge/}" || echo "")

          if [[ -n $PR_NUMBER ]]; then
            BASE_BRANCH=$GITHUB_BASE_REF
          fi

          if [[ $HAS_NODE -eq 1 ]]; then
            # Extract version number from `package.json` file
            echo "version=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT
          fi

          echo "repo-name=$REPO_NAME" >> $GITHUB_OUTPUT
          echo "branch-name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "branch-slug=$BRANCH_SLUG" >> $GITHUB_OUTPUT
          echo "pr-number=$PR_NUMBER" >> $GITHUB_OUTPUT
          echo "base-branch=$BASE_BRANCH" >> $GITHUB_OUTPUT

          # Prepare for `previous-run` and `changed-files` step
          cp -r .github/xyz-actions/.github/scripts .github/
          tree --dirsfirst -aFL 2 .github

      - name: Setup PHP
        if: steps.php.outputs.needs-php == '1'
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
          tools: ${{ steps.php.outputs.php-tools }}
          coverage: none

      - name: Cache dirs
        if: steps.php.outputs.needs-php == '1'
        id: cache-dirs
        env:
          NEEDS_COMPOSER: ${{ steps.php.outputs.needs-composer }}
          NEEDS_WPCLI: ${{ steps.php.outputs.needs-wpcli }}
        run: |
          if [[ $NEEDS_COMPOSER -eq 1 ]]; then
            echo "composer-dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
          fi

          if [[ $NEEDS_WPCLI -eq 1 ]]; then
            echo "wpcli-dir=$(wp cli info --format=json | jq -r '.wp_cli_cache_dir_path')" >> $GITHUB_OUTPUT
          fi

      - name: Reports
        id: reports
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          SHOULD_REPORTS=0

          if [[ -n "${CODECOV_TOKEN}" ]]; then
            echo "has-codecov=1" >> $GITHUB_OUTPUT;
            SHOULD_REPORTS=1
          fi

          if [[ -n "${COVERALLS_REPO_TOKEN}" ]]; then
            echo "has-coveralls=1" >> $GITHUB_OUTPUT;
            SHOULD_REPORTS=1
          fi

          echo "should-reports=${SHOULD_REPORTS}" >> $GITHUB_OUTPUT

      - name: Previous workflow run
        id: previous-run
        uses: actions/github-script@v9
        env:
          CURRENT_BRANCH: ${{ steps.project.outputs.branch-name }}
          TARGET_BRANCH: ${{ steps.project.outputs.base-branch }}
        with:
          script: |
            const { previousRun } = await import('${{github.workspace}}/.github/scripts/previous-run.js');

            return await previousRun({ context, core, exec, github })([
              process.env.CURRENT_BRANCH,
              process.env.TARGET_BRANCH,
            ]);

      - name: Get changed files
        if: |-
          github.event_name != 'workflow_dispatch' &&
          steps.previous-run.outputs.available == '1'
        id: changed-files
        uses: actions/github-script@v9
        continue-on-error: true
        env:
          PREVIOUS_SHA: ${{ fromJSON(steps.previous-run.outputs.result).sha }}
          CURRENT_SHA: ${{ github.sha }}
          NEEDS_PHP: ${{ steps.php.outputs.needs-php }}
          NEEDS_NODE: ${{ steps.node.outputs.needs-node }}
          NODE_PM_NAME: ${{ steps.node.outputs.pm-name }}
        with:
          script: |
            const { changedFiles } = await import('${{github.workspace}}/.github/scripts/changed-files.js');

            return await changedFiles({ context, core, exec, glob })(
              process.env.CURRENT_SHA,
              process.env.PREVIOUS_SHA,
              {
                isPhp: process.env.NEEDS_PHP === '1',
                isNode: process.env.NEEDS_NODE === '1',
                nodePM: process.env.NODE_PM_NAME,
              }
            );
