name: Release

on:
  workflow_call:
    inputs:
      files:
        description: Multiline list of files or wildcards to upload
        required: false
        type: string
        default: ''
      artifact_name:
        description: Name of the artifact to download
        required: false
        type: string
        default: 'release-archives'
      workflow_name:
        description: Name of the workflow to download artifacts from
        required: false
        type: string
        default: ''

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version: lts/*

    - name: Release Changelog
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: npx changelogithub

    - name: File to upload
      id: asset-files
      if: inputs.files == ''
      uses: actions/github-script@v9
      env:
        FILES: ${{ inputs.files }}
        ARTIFACT_NAME: ${{ inputs.artifact_name }}
        WORKFLOW_NAME: ${{ inputs.workflow_name }}
      with:
        result-encoding: string
        script: |
          const { owner, repo } = context.repo;
          const artifact_name = process.env.ARTIFACT_NAME;
          const workflow_name = process.env.WORKFLOW_NAME || process.env.GITHUB_WORKFLOW;

          try {
            const { data: { workflows } } = await github.rest.actions.listRepoWorkflows({ owner, repo });
            const workflow = workflows.find(w => w.name === workflow_name);

            console.log('workflow', workflow)
            if (!workflow) return;

            const { data: { workflow_runs: main_runs } } = await github.rest.actions.listWorkflowRuns({
              branch: 'main',
              event: 'push',
              workflow_id: workflow.id,
              status: 'completed',
              conclusion: 'success',
              per_page: 1,
              owner,
              repo,
            });

            console.log('main_runs', main_runs)
            if (main_runs.length === 0) return;

            const { data: { artifacts } } = await github.rest.actions.listWorkflowRunArtifacts({
              owner,
              repo,
              run_id: main_runs[0].id,
              name: artifact_name,
            });

            console.log('artifacts', artifacts)
            if (artifacts.length === 0) return;

            for (const artifact of artifacts) {
              const download = await github.rest.actions.downloadArtifact({
                owner,
                repo,
                artifact_id: artifact.id,
                archive_format: 'zip',
              });

              console.log(download)
            }

            return '';
          } catch (error) {
            core.setFailed(`Failed to get previous run: ${error.message}`);

            return;
          }

    - name: Upload Release Assets
      if: steps.asset-files.outputs.result != '' || inputs.files != ''
      env:
        ASSET_FILES: ${{ steps.asset-files.outputs.result }}
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        mapfile -t patterns <<< "$FILES"

        shopt -s nullglob

        for pattern in "${patterns[@]}"; do
          p=$(echo "$pattern" | xargs)

          [ -z "$p" ] && continue

          (
            IFS=''
            files=($p)
            if [ ${#files[@]} -eq 0 ]; then
              echo "No files matched pattern: $p"
            else
              echo "::group::Uploading matches for $p..."
              gh release upload "$GITHUB_REF_NAME" "${files[@]}" --clobber
              echo '::endgroup::'
            fi
          )
        done
