name: Report

on:
  workflow_call:
    secrets:
      COVERALLS_REPO_TOKEN:
        required: false
    inputs:
      has-coveralls:
        type: boolean
        default: false

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      has-coveralls: ${{ steps.check-coveralls.outputs.has-coveralls }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Check Coveralls secrets
        if: inputs.has-coveralls == false
        id: check-coveralls
        env:
          HAS_COVERALLS: ${{ inputs.has-coveralls && '1' || '0' }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          # Check existance of Coveralls secrets if not provided via input
          if [ "$HAS_COVERALLS" = "0" ]; then
            HAS_COVERALLS=$([ -n "$COVERALLS_REPO_TOKEN" ] && echo "1" || echo "0")
          fi

          echo "has-coveralls=$HAS_COVERALLS" >> $GITHUB_OUTPUT

  coveralls:
    name: Upload to Coveralls
    if: needs.prepare.outputs.has-coveralls == '1'
    needs: prepare
    runs-on: ubuntu-latest

    steps:
      - name: Coveralls Report
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ github.token }}
          parallel-finished: true
