name: Uploads

on:
  workflow_call:
    inputs:
      files:
        description: Multiline list of files or wildcards to upload
        required: false
        type: string
        default: ''
      artifact_name:
        description: Name of the artifact to download
        required: false
        type: string
        default: 'release-archives'
      branch_name:
        description: Name of the branch to download artifacts from
        required: false
        type: string
        default: 'main'
      workflow_name:
        description: Name of the workflow to download artifacts from
        required: false
        type: string
        default: ''

jobs:
  uploads:
    name: Uploads
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: File to upload
      id: artifact-files
      if: inputs.files == '' && inputs.workflow_name != ''
      uses: actions/github-script@v9
      env:
        BRANCH_NAME: ${{ inputs.branch_name }}
        ARTIFACT_NAME: ${{ inputs.artifact_name }}
        WORKFLOW_NAME: ${{ inputs.workflow_name }}
      with:
        result-encoding: string
        script: |
          const { owner, repo } = context.repo;
          const branch_name = process.env.BRANCH_NAME;
          const artifact_name = process.env.ARTIFACT_NAME;
          const workflow_name = process.env.WORKFLOW_NAME;

          try {
            const { data: { workflows } } = await github.rest.actions.listRepoWorkflows({ owner, repo });
            const workflow = workflows.find(w => w.name === workflow_name);

            if (!workflow) return;

            const { data: { workflow_runs: main_runs } } = await github.rest.actions.listWorkflowRuns({
              branch: branch_name,
              event: 'push',
              workflow_id: workflow.id,
              status: 'completed',
              conclusion: 'success',
              per_page: 1,
              owner,
              repo,
            });

            if (main_runs.length === 0) return;

            const { data: { artifacts } } = await github.rest.actions.listWorkflowRunArtifacts({
              run_id: main_runs[0].id,
              name: artifact_name,
              per_page: 1,
              owner,
              repo,
            });

            if (artifacts.length === 0) return;

            const fs = require('fs')
            const files = []

            for (const artifact of artifacts) {
              const { data: download } = await github.rest.actions.downloadArtifact({
                artifact_id: artifact.id,
                archive_format: 'zip',
                owner,
                repo,
              });

              fs.writeFileSync(`${artifact_name}.zip`, Buffer.from(download));
              fs.mkdirSync(artifact_name, { recursive: true });

              await exec.exec('unzip', [`${artifact_name}.zip`, '-d', `./${artifact_name}`]);

              for (const file of fs.readdirSync(`./${artifact_name}`)) {
                files.push(`${artifact_name}/${file}`);
              }
            }

            console.log(files)
            return files.join('\n');
          } catch (error) {
            core.setFailed(`Failed to get previous run: ${error.message}`);

            return;
          }

    - name: Upload Release Assets
      if: steps.artifact-files.outputs.result != '' || inputs.files != ''
      env:
        LISTED_FILES: ${{ inputs.files }}
        ARTIFACT_FILES: ${{ steps.artifact-files.outputs.result }}
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        FILES="${LISTED_FILES:-$ARTIFACT_FILES}"

        [ -z "$FILES" ] && exit 0

        mapfile -t patterns <<< "$FILES"

        shopt -s nullglob

        for pattern in "${patterns[@]}"; do
          p=$(echo "$pattern" | xargs)

          [ -z "$p" ] && continue

          (
            IFS=''
            files=($p)
            if [ ${#files[@]} -eq 0 ]; then
              echo "No files matched pattern: $p"
            else
              echo "::group::Uploading matches for $p..."
              gh release upload "$GITHUB_REF_NAME" "${files[@]}" --clobber
              echo '::endgroup::'
            fi
          )
        done
